#!/bin/bash

cd /home/search
read -p "Press ENTER to erase current seach indexes (if any) and build new indexes or type ^C to abort" dummy
java -Xmx256M -jar jar/index.jar --db-user musicbrainz --db-name musicbrainz --indexes-dir indexdata --indexes area,artist,releasegroup,release,recording,label,work,tag,annotation,cdstub
